project:
  output-dir: docs

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    theme: cosmo
    embed-resources: true
    code-fold: true
    code-summary: "Show code"
    df-print: kable
    fig-align: center

execute:
  echo: true
  warning: false
  message: false
